### ISSUE TITLE
Feature: Add ability to create Container Registry on DigitalOcean #32

### ISSUE THREAD

**Issue by raz-bn** [crossplane-contrib/provider-digitalocean#42]
### What problem are you facing?
I would like the ability to create a Container Registry using resource definitions with Crossplane.

You can view the API reference here:

 https://docs.digitalocean.com/reference/api/api-reference/#operation/create_registry

and you can also find the godo documentation here:

https://pkg.go.dev/github.com/digitalocean/godo#RegistryCreateRequest

**Comment by ADustyOldMuffin** [comment]
Thanks for suggesting this! I don't have a specific area/group I can think of where this goes. I'd personally put it in the Kubernetes group.
