### ISSUE TITLE
Kubernetes Cluster is using the wrong Godo endpoint for deletion

### ISSUE THREAD

**Issue by ADustyOldMuffin** [crossplane-contrib/provider-digitalocean#45]
### What happened?
When deleting a Kubernetes Cluster, it didn't get deleted.

### How can we reproduce it?
1. Create a Kubernetes Cluster using crossplane
2. Delete the resource and wait for it to be deleted

It should never be deleted.

### What environment did it happen in?
Crossplane version: 

Provider version 0.1.0

This is caused by the Kubernetes controller calling `godo.Database.Delete`

**Comment by irizzant** [comment]
Hitting the same here
