### ISSUE TITLE
DOK kubeconfig secret not created

### ISSUE THREAD

**Issue by vfarcic** [crossplane-contrib/provider-digitalocean#47]
### What happened?

When working with Kubernetes cluster resources, Crossplane creates a secret that can be used by other resources. In case of DOK, the secret is not created.

### How can we reproduce it?

Create a DOK cluster and check whether the secrets with kubeconfig were created in `crossplane-system` and the claim Namespace (if using claims).

**Comment by ADustyOldMuffin** [comment]
Hello, thanks for this! This is more than likely the same cause as
 https://github.com/crossplane-contrib/provider-digitalocean/pull/34

I'll look into this as it should hopefully be a straight forward fix.

**Comment by vfarcic** [comment]
Do you have a rough idea when we might get a release with this and other fixes?

**Comment by ADustyOldMuffin** [comment]
We have some pending PRs that need reviews. You can always use the `rc` tags to get the latest changes if you'd like.
