### ISSUE TITLE
Add missing droplet creation fields to resource definitions

### ISSUE THREAD

**Issue by ADustyOldMuffin** [crossplane-contrib/provider-digitalocean#7]
### What problem are you facing?

I wish to be able to specify the `with_droplet_agent` field and the `user_data` field on a new droplet resource.

You can find the godo docs [here](https://pkg.go.dev/github.com/digitalocean/godo#DropletCreateRequest)
and the actual API docs [here](https://docs.digitalocean.com/reference/api/api-reference/#operation/create_droplet)

### What are your proposed solutions?

Adding these fields to the resource definition. The `with_droplet_agent` is fairly straight forward, but the `user_data` can be done in several different ways so I'm open to suggestions/ideas.

**Comment by tillepille** [comment]
Should have discovered this issue earlier, missed my hacktoberfest goals :( 

I already started working on the `with_droplet_agent` config flag but its not finished yet.

for the `userdata`: Which approaches do you see? 
The naive first idea would be just the string, maybe b64 encoded.
My second idea would be a ConfigMap to separate such "bigger" strings from the rest, but this adds some complexity to the operator imho. And I don't believe, I am capable of this... 😬

**Comment by ADustyOldMuffin** [comment]
> Should have discovered this issue earlier, missed my hacktoberfest goals :( 
> 
> I already started working on the `with_droplet_agent` config flag but its not finished yet.
> 
> for the `userdata`: Which approaches do you see? 
> The naive first idea would be just the string, maybe b64 encoded.
> My second idea would be a ConfigMap to separate such "bigger" strings from the rest, but this adds some complexity to the operator imho. And I don't believe, I am capable of this... 😬 

I believe a config map or secret would work, you would have to setup a config map selector, but if you're not comfortable doing that then a PR to add the single field is fine!

**Comment by tillepille** [comment]
Regarding user data: 
since for AWS (IMHO for the most supply-tools,eg. terraform, the gold standard) it's [also done as a b64 string](https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/Instance/v1alpha1@v0.22.0#spec-forProvider-userData), I would do it like this as well.
