### ISSUE TITLE
Create a Repeatable CONTRIBUTING guide

### ISSUE THREAD

**Issue by yordis** [crossplane-contrib/provider-digitalocean#78]
I am trying to contribute to the package, but I haven't been able to follow the https://github.com/crossplane-contrib/provider-digitalocean/blob/main/docs/CONTRIBUTING.md

<img width="1606" alt="Screenshot 2023-05-31 at 2 26 19 PM" src="https://github.com/crossplane-contrib/provider-digitalocean/assets/4237280/607206ae-127c-492d-ae49-f1065cb97a30">

Ideally, the contributing guide has a repeatable [how-to guide](https://diataxis.fr/how-to-guides/) that people could follow and be able to contribute to the project.

**Comment by jbw976** [comment]
thanks for sharing your experience @yordis!! looks like you can run `make submodules` to get the build submodule cloned, and then make will have what it needs to start running.

Agreed on updating the contributing guide to have repeatable steps for new contributors 🤓
